### ISSUE TITLE
Convert from egg to wheel

### ISSUE THREAD

**Issue by gonsie** [LLNL/py-hostlist#1]
The python community is great because there is a ton of documentation online... but some of the documentation is out dated and stale. Recently, the community has moved to using wheels for packaging, rather than eggs: 
- [Wheel vs Egg](https://packaging.python.org/discussions/wheel-vs-egg/)
- [PyPI wheel packaging guide](https://packaging.python.org/tutorials/packaging-projects/)

If you got the egg packaging instructions from the LC confluence pages we'll have to make sure they get updated.

**Comment by cmoussa1** [comment]
I believe I followed the wheel packaging instructions when I initially built py-hostlist. In `py-hostlist/dist`, the following files are listed:

```
py-hostlist-0.0.1.tar.gz
py_hostlist-0.0.1-py3-none-any.whl
```

which is what should result from generating the distribution archives using wheel. I apologize if I'm misunderstanding! Let me know if I have it wrong.

**Comment by gonsie** [comment]
Ah, the -egg.info file was throwing me off. Feel free to close this issue :)
