### ISSUE TITLE
Call -h in Travis

### ISSUE THREAD

**Issue by gonsie** [LLNL/py-hostlist#25]
@IanLee1521 recommends that our Travis CI testing calls `hostlist -h` just to make sure it works.

**Comment by cmoussa1** [comment]
Hmm... just using `hostlist -h` results in a failed build. We get the following error:

```
hostlist: command not found
The command "hostlist -h" exited with 127.
```

Do we need to use any other commands in our `.travis.yml` file before running `hostlist -h`? Are we getting this error because we need to build our project first?

**Comment by cmoussa1** [comment]
Going to open another branch `hostlist-cmd-travis` to address this issue.

**Comment by gonsie** [comment]
We definitely need to build our project first. Once our project is built and installed, running `hostlist -h` should succeed.

**Comment by cmoussa1** [comment]
Got it working! You were right - once we added build and install commands to `.travis.yml`, the `hostlist -h` command works just fine.
